-- William Alejandro Borrayo Alarcón - 201909103

SELECT COUNT(*) FROM TEMPORAL;
SELECT COUNT(*) FROM DIRECCION;
SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) FROM EMPLEADO;
SELECT COUNT(*) FROM TIENDA;
SELECT COUNT(*) FROM PELICULA;
SELECT COUNT(*) FROM ACTOR;
SELECT COUNT(*) FROM RENTA;





					
					 
