-- Database: practica

-- DROP DATABASE practica;

CREATE DATABASE practica
    WITH 
    OWNER = william
    ENCODING = 'UTF8'
    LC_COLLATE = 'es_GT.UTF-8'
    LC_CTYPE = 'es_GT.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
--------------------------------------------------- TEMPORAL ---------------------------------------------------
CREATE TABLE IF NOT EXISTS PUBLIC.TEMPORAL(
    NOMBRE_CLIENTE VARCHAR,
	CORREO_CLIENTE VARCHAR,
	CLIENTE_ACTIVO VARCHAR,
	FECHA_CREACION VARCHAR,
	TIENDA_PREFERIDA VARCHAR,
	DIRECCION_CLIENTE VARCHAR,
	CODIGO_POSTAL_CLIENTE VARCHAR,
	CIUDAD_CLIENTE VARCHAR,
	PAIS_CLIENTE VARCHAR,
	FECHA_RENTA VARCHAR,
	FECHA_RETORNO VARCHAR,
	MONTO_A_PAGAR VARCHAR,
	FECHA_PAGO VARCHAR,
	NOMBRE_EMPLEADO VARCHAR,
	CORREO_EMPLEADO VARCHAR,
	EMPLEADO_ACTIVO VARCHAR,
	TIENDA_EMPLEADO VARCHAR,
	USUARIO_EMPLEADO VARCHAR,
	CONTRASENIA_EMPLEADO VARCHAR,
	DIRECCION_EMPLEADO VARCHAR,
	CODIGO_POSTAL_EMPLEADO VARCHAR,
	CIUDAD_EMPLEADO VARCHAR,
	PAIS_EMPLEADO VARCHAR,
	NOMBRE_TIENDA VARCHAR,
	ENCARGADO_TIENDA VARCHAR,
	DIRECCION_TIENDA VARCHAR,
	CODIGO_POSTAL_TIENDA VARCHAR,
	CIUDAD_TIENDA VARCHAR,
	PAIS_TIENDA VARCHAR,
	TIENDA_PELICULA VARCHAR,
	NOMBRE_PELICULA VARCHAR,
	DESCRIPCION_PELICULA VARCHAR,
	ANIO_LANZAMIENTO VARCHAR,
	DIAS_RENTA VARCHAR,
	COSTO_RENTA VARCHAR,
	DURACION VARCHAR,
	COSTO_POR_DANIO VARCHAR,
	CLASIFICACION VARCHAR,
	LENGUAJE_PELICULA VARCHAR,
	CATEGORIA_PELICULA VARCHAR,
	ACTOR_PELICULA VARCHAR
	);
	
ALTER TABLE public.TEMPORAL
    OWNER to william;

SELECT * FROM TEMPORAL;

DROP TABLE TEMPORAL;

COPY PUBLIC.TEMPORAL FROM '/tmp/BlockbusterData.csv' DELIMITER ';' CSV HEADER;

--------------------------------------------------- MODELO ER ---------------------------------------------------

------------------------------------------------------------------------- TABLA DIRECCION
CREATE TABLE IF NOT EXISTS PUBLIC.DIRECCION(
	idDireccion SERIAL PRIMARY KEY,
	Domicilio VARCHAR,  -- Para lo que dice direccion
	CodigoPostal VARCHAR,
	Ciudad VARCHAR,
	Pais VARCHAR
);

-- Se insertan las direcciones de clientes
INSERT INTO DIRECCION (Domicilio, CodigoPostal, Ciudad, Pais)
SELECT DISTINCT DIRECCION_CLIENTE, CODIGO_POSTAL_CLIENTE, CIUDAD_CLIENTE, PAIS_CLIENTE from TEMPORAL
WHERE NOT EXISTS(SELECT FROM DIRECCION WHERE 
				 Domicilio=DIRECCION_CLIENTE and
				 CodigoPostal=CODIGO_POSTAL_CLIENTE and
				 Ciudad=CIUDAD_CLIENTE and
				 Pais=PAIS_CLIENTE) and
				 not(DIRECCION_CLIENTE='-' and CODIGO_POSTAL_CLIENTE='-' and CIUDAD_CLIENTE='-' and PAIS_CLIENTE='-') and
				 not(NOMBRE_CLIENTE='-') and
				 not(NOMBRE_TIENDA='-') and
				 not(NOMBRE_EMPLEADO='-');

-- Se insertan las direcciones de Empleados
INSERT INTO DIRECCION (Domicilio, CodigoPostal, Ciudad, Pais)
SELECT DISTINCT DIRECCION_EMPLEADO, CODIGO_POSTAL_EMPLEADO, CIUDAD_EMPLEADO, PAIS_EMPLEADO FROM TEMPORAL
WHERE NOT EXISTS(SELECT FROM DIRECCION WHERE 
				 Domicilio=DIRECCION_EMPLEADO and
				 CodigoPostal=CODIGO_POSTAL_EMPLEADO and
				 Ciudad=CIUDAD_EMPLEADO and
				 Pais=PAIS_EMPLEADO) and
				 not(DIRECCION_EMPLEADO='-' and CODIGO_POSTAL_EMPLEADO='-' and CIUDAD_EMPLEADO='-' and PAIS_EMPLEADO='-') and
				 not(NOMBRE_CLIENTE='-') and
				 not(NOMBRE_TIENDA='-') and
				 not(NOMBRE_EMPLEADO='-');
				 
-- Se insertan las direcciones de Tiendas
INSERT INTO DIRECCION (Domicilio, CodigoPostal, Ciudad, Pais)
SELECT DISTINCT DIRECCION_TIENDA, CODIGO_POSTAL_TIENDA, CIUDAD_TIENDA, PAIS_TIENDA FROM TEMPORAL
WHERE NOT EXISTS(SELECT FROM DIRECCION WHERE 
				 Domicilio=DIRECCION_TIENDA and
				 CodigoPostal=CODIGO_POSTAL_TIENDA and
				 Ciudad=CIUDAD_TIENDA and
				 Pais=PAIS_TIENDA) and
				 not(DIRECCION_TIENDA='-' and CODIGO_POSTAL_TIENDA='-' and CIUDAD_TIENDA='-' and PAIS_TIENDA='-') and
				 not(NOMBRE_CLIENTE='-') and
				 not(NOMBRE_TIENDA='-') and
				 not(NOMBRE_EMPLEADO='-');
					 
SELECT * FROM DIRECCION;
				 
------------------------------------------------------------------------- TABLA CLIENTE
CREATE TABLE IF NOT EXISTS PUBLIC.CLIENTE(
	Nombre VARCHAR, 
	Apellido VARCHAR,
	Correo VARCHAR PRIMARY KEY,
	Activo VARCHAR,
	FechaRegistro VARCHAR,
	TiendaPreferida VARCHAR,
	idDireccion INTEGER,
	Rentas INTEGER,
	FOREIGN KEY (idDireccion)
	REFERENCES DIRECCION(idDireccion)
);

INSERT INTO CLIENTE
  SELECT 
  split_part(NOMBRE_CLIENTE, ' ', 1),
  split_part(NOMBRE_CLIENTE, ' ', 2),
  CORREO_CLIENTE,
  CLIENTE_ACTIVO,
  FECHA_CREACION,
  TIENDA_PREFERIDA,
  (SELECT idDireccion FROM DIRECCION WHERE Domicilio=DIRECCION_CLIENTE)
  FROM TEMPORAL
   WHERE not (
	   NOMBRE_CLIENTE='-' and 
	   CORREO_CLIENTE='-' and 
	   CLIENTE_ACTIVO='-' and 
	   FECHA_CREACION='-' and
	   TIENDA_PREFERIDA='_') and not (CORREO_CLIENTE='-')
	   and EXISTS(SELECT idDireccion FROM DIRECCION WHERE Domicilio=DIRECCION_CLIENTE)
   ON CONFLICT (Correo)
DO NOTHING;

------------------------------------------------------------------------- TABLA EMPLEADO
CREATE TABLE IF NOT EXISTS PUBLIC.EMPLEADO(
	Nombre VARCHAR, 
	Apellido VARCHAR,
	Correo VARCHAR PRIMARY KEY,
	Activo VARCHAR,
	TiendaAsignada VARCHAR,
	Usuario VARCHAR,
	Contrasenia VARCHAR,
	idDireccion INTEGER,
	FOREIGN KEY (idDireccion)
	REFERENCES DIRECCION(idDireccion)
);

INSERT INTO EMPLEADO
  SELECT 
  split_part(NOMBRE_EMPLEADO, ' ', 1),
  split_part(NOMBRE_EMPLEADO, ' ', 2),
  CORREO_EMPLEADO,
  EMPLEADO_ACTIVO,
  TIENDA_EMPLEADO,
  USUARIO_EMPLEADO,
  CONTRASENIA_EMPLEADO,
  (SELECT idDireccion FROM DIRECCION WHERE Domicilio=DIRECCION_CLIENTE)
  FROM TEMPORAL
   WHERE not (
	   NOMBRE_EMPLEADO='-' and 
	   CORREO_EMPLEADO='-' and 
	   EMPLEADO_ACTIVO='-' and 
	   TIENDA_EMPLEADO='-' and
	   USUARIO_EMPLEADO='_' and
	   CONTRASENIA_EMPLEADO='_' and
   	   DIRECCION_EMPLEADO='-' and 
	   CODIGO_POSTAL_EMPLEADO='-' and 
	   CIUDAD_EMPLEADO='-' and 
	   PAIS_EMPLEADO='-') and not (CORREO_EMPLEADO='-')
	   and EXISTS(SELECT idDireccion FROM DIRECCION WHERE Domicilio=DIRECCION_EMPLEADO)
   ON CONFLICT (Correo)
DO NOTHING;

------------------------------------------------------------------------- TABLA TIENDA
CREATE TABLE IF NOT EXISTS PUBLIC.TIENDA(
	Nombre VARCHAR PRIMARY KEY, 
	EncargadoNombre VARCHAR,
	EncargadoApellido VARCHAR,
	idDireccion INTEGER,
	FOREIGN KEY (idDireccion)
	REFERENCES DIRECCION(idDireccion)
);

INSERT INTO TIENDA
  SELECT 
  NOMBRE_TIENDA,
  split_part(ENCARGADO_TIENDA, ' ', 1),
  split_part(ENCARGADO_TIENDA, ' ', 2),
  (SELECT idDireccion FROM DIRECCION WHERE Domicilio=DIRECCION_CLIENTE)
  FROM TEMPORAL
   WHERE not (
	   NOMBRE_TIENDA='-' and 
	   ENCARGADO_TIENDA='-' and 
	   EMPLEADO_ACTIVO='-' and 
	   TIENDA_EMPLEADO='-' and
	   USUARIO_EMPLEADO='_' and
	   CONTRASENIA_EMPLEADO='_' and
   	   DIRECCION_EMPLEADO='-') and not NOMBRE_TIENDA='-'
	   and EXISTS(SELECT idDireccion FROM DIRECCION WHERE Domicilio=DIRECCION_TIENDA)
   ON CONFLICT (Nombre)
DO NOTHING;

------------------------------------------------------------------------- TABLA PELICULA
CREATE TABLE IF NOT EXISTS PUBLIC.PELICULA(
	Tienda VARCHAR,
	Nombre VARCHAR PRIMARY KEY,
	Descripcion VARCHAR,
	AnioLanzamiento VARCHAR,
	DiasRenta VARCHAR,
	CostoRenta VARCHAR,
	Duracion VARCHAR,
	CostoDanio VARCHAR,
	Clasificacion VARCHAR,
	Lenguaje VARCHAR,
	Categoria VARCHAR,
	Cantidad INTEGER,
	FOREIGN KEY(Tienda)
	REFERENCES TIENDA(Nombre)
);

INSERT INTO PELICULA
SELECT 
TIENDA_PELICULA,
NOMBRE_PELICULA,
DESCRIPCION_PELICULA,
ANIO_LANZAMIENTO,
DIAS_RENTA,
COSTO_RENTA,
DURACION,
COSTO_POR_DANIO,
CLASIFICACION,
LENGUAJE_PELICULA,
CATEGORIA_PELICULA
FROM TEMPORAL
WHERE not TIENDA_PELICULA='-'
	  and not NOMBRE_PELICULA='-'
	  and EXISTS (SELECT Nombre FROM TIENDA WHERE Nombre=TIENDA_PELICULA)
ON CONFLICT(Nombre)
DO NOTHING;

------------------------------------------------------------------------- TABLA ACTOR
CREATE TABLE IF NOT EXISTS PUBLIC.ACTOR(
	NombreCompleto VARCHAR,
	Nombre VARCHAR,
	Apellido VARCHAR,
	Pelicula VARCHAR,
	PRIMARY KEY (NombreCompleto, Pelicula),
	FOREIGN KEY (Pelicula) REFERENCES PELICULA(Nombre)
);

INSERT INTO ACTOR
SELECT DISTINCT
  ACTOR_PELICULA,
  split_part(ACTOR_PELICULA, ' ', 1),
  split_part(ACTOR_PELICULA, ' ', 2),
  NOMBRE_PELICULA
FROM TEMPORAL
WHERE NOT(ACTOR_PELICULA='-' and NOMBRE_PELICULA='-')
	and EXISTS(SELECT Nombre FROM PELICULA WHERE Nombre=NOMBRE_PELICULA) -- HACER ESTO CON LAS LLAVES FORANEAS
   ON CONFLICT (NombreCompleto, Pelicula)
DO NOTHING;
				 
------------------------------------------------------------------------- TABLA RENTA
CREATE TABLE IF NOT EXISTS PUBLIC.RENTA(
	idRenta SERIAL PRIMARY KEY,
	FechaRenta VARCHAR,
	FechaRetorno VARCHAR,
	MontoPagar DECIMAL,
	FechaPago VARCHAR,
	Cliente VARCHAR,
	Tienda VARCHAR,
	Pelicula VARCHAR,
	FOREIGN KEY (Cliente) REFERENCES CLIENTE(Correo),
	FOREIGN KEY (Tienda) REFERENCES TIENDA(Nombre),
	FOREIGN KEY (Pelicula) REFERENCES PELICULA(Nombre)
);

INSERT INTO RENTA (FechaRenta, FechaRetorno, MontoPagar, FechaPago, Cliente, Tienda, Pelicula)
SELECT DISTINCT
  FECHA_RENTA,
  FECHA_RETORNO,
  MONTO_A_PAGAR::DECIMAL,
  FECHA_PAGO,
  CORREO_CLIENTE,
  NOMBRE_TIENDA,
  NOMBRE_PELICULA
FROM TEMPORAL
WHERE NOT EXISTS (SELECT FROM RENTA WHERE FechaRenta=FECHA_RENTA and
				 FechaRetorno=FECHA_RETORNO and MontoPagar=MONTO_A_PAGAR::DECIMAL and
				 FechaPago=FECHA_PAGO and Cliente=CORREO_CLIENTE and
				 Tienda=NOMBRE_TIENDA and Pelicula=NOMBRE_PELICULA)
				 and not FECHA_RENTA='-'
				 and not NOMBRE_CLIENTE='-'
				 and EXISTS (SELECT Correo FROM CLIENTE WHERE Correo=CORREO_CLIENTE)
				 and EXISTS (SELECT Nombre FROM TIENDA WHERE Nombre=NOMBRE_TIENDA)
				 and EXISTS (SELECT Nombre FROM PELICULA WHERE Nombre=NOMBRE_PELICULA);
			
-- Se actualizan las rentas para cada cliente
UPDATE CLIENTE CF SET Rentas=(SELECT COUNT(*) FROM RENTA INNER JOIN CLIENTE CL ON RENTA.Cliente=CL.Correo 
WHERE CL.Nombre=CF.Nombre and CL.Apellido=CF.Apellido and CL.Correo=CF.Correo);

-- Para actualizar la cantidad de cada pelicula
UPDATE PELICULA SET Cantidad=(SELECT COUNT(*) FROM 
(SELECT DISTINCT Pelicula, FechaRenta, Cliente FROM RENTA WHERE Pelicula=Nombre) AS FOO);
				
DROP TABLE IF EXISTS RENTA;
DROP TABLE IF EXISTS ACTOR;
DROP TABLE IF EXISTS PELICULA;
DROP TABLE IF EXISTS TIENDA;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS DIRECCION;
--DROP TABLE TEMPORAL;
SELECT * FROM RENTA;
SELECT * FROM ACTOR;
SELECT * FROM PELICULA;
SELECT * FROM TIENDA;
SELECT * FROM EMPLEADO;
SELECT * FROM CLIENTE;
SELECT * FROM DIRECCION;
SELECT * FROM TEMPORAL;

--------------------------------------------------- CONSULTAS ---------------------------------------------------
-- 1)
-- RESULTADO = 17	 
SELECT Nombre, Cantidad FROM PELICULA WHERE Nombre='SUGAR WONKA';
					 
-- 2)
-- RESULTADO = 7 CLIENTES
SELECT DISTINCT CLIENTE.Nombre, CLIENTE.Apellido, 
					 (SELECT SUM(CAST(RENTA1.MontoPagar AS DECIMAL)) FROM RENTA RENTA1 INNER JOIN CLIENTE CLIENTE1 
					  ON RENTA1.Cliente = CLIENTE1.Correo WHERE CLIENTE1.Correo=CLIENTE.Correo)as Monto 
FROM CLIENTE INNER JOIN RENTA ON CLIENTE.Correo = RENTA.Cliente 
WHERE CLIENTE.Rentas >39;					 
					
-- 3) 
SELECT DISTINCT NombreCompleto FROM ACTOR WHERE (position('son' in LOWER(Apellido))>0) ORDER BY NombreCompleto ASC;

-- 4)
SELECT PELICULA.Nombre, PELICULA.Descripcion, ACTOR.NombreCompleto, Pelicula.AnioLanzamiento
FROM PELICULA INNER JOIN ACTOR ON PELICULA.Nombre = ACTOR.Pelicula 
WHERE( (position('crocodile' in LOWER(PELICULA.Descripcion))>0) and 
	   (position('shark' in LOWER(PELICULA.Descripcion))>0) and
	 	not ACTOR.NombreCompleto='-') 
ORDER BY ACTOR.Apellido ASC;

-- 5)
SELECT DISTINCT DIRECCION.Pais, CLIENTE.Nombre, CLIENTE.Apellido,
					 CONCAT(ROUND(((CLIENTE.Rentas)::DECIMAL*100
								   /
					(SELECT SUM(Rentas) FROM CLIENTE CL  INNER JOIN DIRECCION DR
					 ON CL.idDireccion=DR.idDireccion
					 WHERE DR.Pais=DIRECCION.Pais)::DECIMAL)::DECIMAL, 2),' %') as porcentaje 
FROM DIRECCION INNER JOIN CLIENTE ON DIRECCION.idDireccion = CLIENTE.idDireccion 
WHERE CLIENTE.Rentas = (SELECT MAX (Rentas) FROM CLIENTE);
	 
-- 6)
SELECT DISTINCT (SELECT COUNT(*) FROM CLIENTE) AS TOTAL_CLIENTES, D.Pais, D.Ciudad, CONCAT(ROUND((
	SELECT COUNT(*)
	FROM DIRECCION INNER JOIN CLIENTE ON DIRECCION.idDireccion = CLIENTE.idDireccion
	WHERE DIRECCION.Pais=D.Pais AND DIRECCION.Ciudad=D.Ciudad
	GROUP BY DIRECCION.Pais, DIRECCION.Ciudad)::DECIMAL*100
					 /
	(SELECT COUNT(*)
	FROM DIRECCION INNER JOIN CLIENTE ON DIRECCION.idDireccion = CLIENTE.idDireccion
	WHERE DIRECCION.Pais=D.Pais
	GROUP BY DIRECCION.Pais)::DECIMAL, 2), ' %') as Porcentaje
FROM DIRECCION D ORDER BY D.Pais ASC;

-- 7)  
-- promedio = (rentas totales pais y ciudad)/(no.ciudades por pais) DEFINITIVE
SELECT DISTINCT DP.Pais, DP.Ciudad, (SELECT COUNT(*)
									FROM RENTA
									INNER JOIN CLIENTE ON RENTA.Cliente = CLIENTE.Correo
									INNER JOIN DIRECCION ON CLIENTE.idDireccion = DIRECCION.idDireccion
									WHERE DIRECCION.Pais=DP.Pais and DIRECCION.Ciudad=DP.Ciudad) AS Rentas,
	(
	ROUND((SELECT COUNT(*)
				FROM RENTA
				INNER JOIN CLIENTE ON RENTA.Cliente = CLIENTE.Correo
				INNER JOIN DIRECCION ON CLIENTE.idDireccion = DIRECCION.idDireccion
				WHERE DIRECCION.Pais=DP.Pais and DIRECCION.Ciudad=DP.Ciudad)::DECIMAL
							/
	(SELECT COUNT(*) FROM DIRECCION DCP WHERE DCP.Pais=DP.Pais GROUP BY DCP.Pais)::DECIMAL,2)
	)AS Promedio
FROM DIRECCION DP ORDER BY DP.Pais ASC, DP.Ciudad ASC;

--8)
--porcentaje de rentas=(rentas de sport por pais)*100 / (rentas por pais)
SELECT DISTINCT DP.Pais, CONCAT(ROUND((
	(SELECT COUNT(*)
		FROM RENTA RENTA2
		INNER JOIN CLIENTE CLIENTE2  ON RENTA2.Cliente = CLIENTE2.Correo
		INNER JOIN PELICULA PELICULA2 ON RENTA2.Pelicula = PELICULA2.Nombre
		INNER JOIN DIRECCION DIRECCION2 ON CLIENTE2.idDireccion = DIRECCION2.idDireccion
		WHERE DIRECCION2.Pais=DP.Pais and PELICULA2.Categoria='Sports' HAVING COUNT(*)>0)::DECIMAL*100
		/
	NULLIF((SELECT DISTINCT COUNT(*)
		FROM RENTA RENTA1
		INNER JOIN CLIENTE CLIENTE1  ON RENTA1.Cliente = CLIENTE1.Correo
		INNER JOIN PELICULA PELICULA1 ON RENTA1.Pelicula = PELICULA1.Nombre
		INNER JOIN DIRECCION DIRECCION1 ON CLIENTE1.idDireccion = DIRECCION1.idDireccion
		WHERE DIRECCION1.Pais=DP.Pais
	    HAVING COUNT(*)>0)::DECIMAL,0)
		),2), ' %') AS PORCENTAJE_SPORTS
FROM DIRECCION DP ORDER BY DP.Pais ASC;
					 				 
--9)
SELECT DP.Ciudad, (SELECT COUNT(*)
						FROM RENTA 
						INNER JOIN CLIENTE ON RENTA.Cliente = CLIENTE.Correo
						INNER JOIN PELICULA ON RENTA.Pelicula = PELICULA.Nombre
						INNER JOIN DIRECCION ON CLIENTE.idDireccion = DIRECCION.idDireccion
						WHERE (DIRECCION.Pais='United States' or DIRECCION.Pais='Estados Unidos') and
						 DIRECCION.Ciudad=DP.Ciudad) AS Rentas	 
FROM DIRECCION DP WHERE (DP.Pais='United States' or DP.Pais='Estados Unidos') and
					 -- rentas > rentas dayton
						(SELECT COUNT(*)
						FROM RENTA RENTA1 
						INNER JOIN CLIENTE CLIENTE1 ON RENTA1.Cliente = CLIENTE1.Correo
						INNER JOIN PELICULA PELICULA1 ON RENTA1.Pelicula = PELICULA1.Nombre
						INNER JOIN DIRECCION DIRECCION1 ON CLIENTE1.idDireccion = DIRECCION1.idDireccion
						WHERE (DIRECCION1.Pais='United States' or DIRECCION1.Pais='Estados Unidos') and
						 DIRECCION1.Ciudad=DP.Ciudad)
						 >
						(SELECT COUNT(*)
						FROM RENTA RENTA2
						INNER JOIN CLIENTE CLIENTE2 ON RENTA2.Cliente = CLIENTE2.Correo
						INNER JOIN PELICULA PELICULA2 ON RENTA2.Pelicula = PELICULA2.Nombre
						INNER JOIN DIRECCION DIRECCION2 ON CLIENTE2.idDireccion = DIRECCION2.idDireccion
						WHERE DIRECCION2.Ciudad='Dayton')
					 ORDER BY DP.Ciudad ASC;
					 
--10)
--CUIDADES POR PAIS EN RENTAS
DROP TABLE IF EXISTS CONT_CAT;
CREATE TEMP TABLE IF NOT EXISTS CONT_CAT AS 				 
	SELECT DISTINCT DIRECCION.Ciudad, DIRECCION.Pais, PELICULA.Categoria, COUNT(*) AS CONT
	FROM RENTA 
	INNER JOIN CLIENTE ON RENTA.Cliente = CLIENTE.Correo
	INNER JOIN PELICULA ON RENTA.Pelicula = PELICULA.Nombre
	INNER JOIN DIRECCION ON CLIENTE.idDireccion = DIRECCION.idDireccion 
	GROUP BY DIRECCION.Ciudad, DIRECCION.Pais, PELICULA.Categoria
	ORDER BY Direccion.Pais ASC;

SELECT CF.Ciudad, CF.Pais FROM CONT_CAT CF
 WHERE CF.CONT=(SELECT MAX (CONT) FROM CONT_CAT CC WHERE CC.Ciudad=CF.Ciudad and CC.Pais=CF.Pais)
 and CF.Categoria='Horror';
				
--------------------------------------------------- CONTEOS ---------------------------------------------------
SELECT COUNT(*) FROM TEMPORAL;
SELECT COUNT(*) FROM DIRECCION;
SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) FROM EMPLEADO;
SELECT COUNT(*) FROM TIENDA;
SELECT COUNT(*) FROM PELICULA;
SELECT COUNT(*) FROM ACTOR;
SELECT COUNT(*) FROM RENTA;
